
name: My GGI Deploy deployment
run-name: Deploying your own GGI!
on:
  push:
    branches:
      - main
jobs:
  deploy-ggi:
    name: Deploy board
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: GGI Deploy
        env:
          GGI_GITHUB_TOKEN: ${{ secrets.GGI_GITHUB_TOKEN }}
        run: |
          python scripts/ggi_deploy_github.py -a -d -p
  update-website:
    name: Update website
    needs: deploy-ggi
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: GGI Update website
        env:
          GGI_GITHUB_TOKEN: ${{ secrets.GGI_GITHUB_TOKEN }}
        run: |
          python scripts/ggi_update_website_github.py

